export const DEFAULT_PROMOTIONS=Object.freeze([{id:'seasonal-heritage',name:'Heritage Season',type:'Seasonal campaign',active:true,featuredCollection:'Heritage edit',startsAt:'2026-01-01',endsAt:'2026-12-31',message:'Carry the meaning.'}]);
export const DEFAULT_DISCOUNT_CODES=Object.freeze([{id:'WELCOME10',code:'WELCOME10',type:'percentage',value:10,minOrderValue:50,maxDiscount:100,startsAt:'2026-01-01',endsAt:'2026-12-31',usageLimit:1000,customerUsageLimit:1,used:0,active:true}]);
export const DEFAULT_LOYALTY_RULES=Object.freeze({pointsPerCurrency:1,redemptionValue:0.01,minimumRedemption:100,referralReward:250});
export function validateDiscount(code,{subtotal,items=[],customerUses=0,now=new Date()}={}){if(!code||!code.active)return {valid:false,reason:'Code is inactive.'};if(new Date(code.startsAt)>now||new Date(code.endsAt)<now)return {valid:false,reason:'Code is outside its valid dates.'};if(code.usageLimit&&code.used>=code.usageLimit)return {valid:false,reason:'Code usage limit reached.'};if(code.customerUsageLimit&&customerUses>=code.customerUsageLimit)return {valid:false,reason:'Customer usage limit reached.'};if(subtotal<code.minOrderValue)return {valid:false,reason:`Minimum order value is ${code.minOrderValue}.`};const applicable=items.filter(i=>(!code.productIds?.length||code.productIds.includes(i.productId))&&(!code.categories?.length||code.categories.includes(i.category)));if(code.productIds?.length||code.categories?.length){if(!applicable.length)return {valid:false,reason:'Code does not apply to these products.'};}const base=applicable.length?applicable.reduce((n,i)=>n+i.price*i.quantity,0):subtotal;const raw=code.type==='fixed'?code.value:base*(code.value/100);return {valid:true,amount:Math.min(raw,code.maxDiscount||Infinity),base};}
export function createGiftCard({value,expiresAt=null,createdBy='admin'}){const code=`KG-${Math.random().toString(36).slice(2,8).toUpperCase()}-${Date.now().toString(36).slice(-4).toUpperCase()}`;return {id:`gift_${Date.now()}`,code,value,balance:value,expiresAt,createdAt:new Date().toISOString(),createdBy,usageHistory:[],active:true};}
export function redeemGiftCard(card,amount,orderId,now=new Date()){if(!card?.active)return {ok:false,reason:'Gift card inactive.'};if(card.expiresAt&&new Date(card.expiresAt)<now)return {ok:false,reason:'Gift card expired.'};if(amount<=0||amount>card.balance)return {ok:false,reason:'Gift card balance is insufficient.'};return {ok:true,card:{...card,balance:card.balance-amount,usageHistory:[...card.usageHistory,{orderId,amount,at:now.toISOString()}]}};}
export function awardPoints(balance,amount,source,reference){const points=Math.max(0,Math.floor(amount));return {balance:balance+points,transaction:{id:`lp_${Date.now()}`,type:'earned',points,source,reference,at:new Date().toISOString()}};}
export function redeemPoints(balance,points,source,reference,rules=DEFAULT_LOYALTY_RULES){if(points<rules.minimumRedemption||points>balance)return {ok:false,reason:'Points cannot be redeemed.'};return {ok:true,balance:balance-points,discount:points*rules.redemptionValue,transaction:{id:`lp_${Date.now()}`,type:'redeemed',points,source,reference,at:new Date().toISOString()}};}
export function createReferral(referrerId){return {code:`KGREF-${referrerId}-${Math.random().toString(36).slice(2,7).toUpperCase()}`,referrerId,createdAt:new Date().toISOString(),uses:[]};}
export function recordReferral(referral,referredCustomerId,orderId,reward){return {...referral,uses:[...referral.uses,{referredCustomerId,orderId,reward,qualifyingPurchase:true,at:new Date().toISOString()}]};}
export function culturalSearch(products,query){const q=query.trim().toLowerCase();if(!q)return products;return products.filter(p=>[p.kenteName,p.meaning,p.symbolism,p.pattern,p.origin,p.region,p.country,p.culturalSignificance,p.historicalContext,p.weaverStory,p.productStory,...(p.culturalConcepts||[])].filter(Boolean).join(' ').toLowerCase().includes(q));}
export function recommend(products,{currentId,viewedIds=[]}={}){const current=products.find(p=>p.id===currentId);return products.filter(p=>p.status==='Published'&&p.stock>0&&p.id!==currentId).sort((a,b)=>{const score=p=>((viewedIds.includes(p.id)?3:0)+(current&&p.category===current.category?2:0)+(current&&p.region===current.region?1:0)+(p.featured?1:0));return score(b)-score(a)}).slice(0,4);}
